import headerLogo from './header-logo.svg'
import headerSearch  from './search.svg'
import mainFishEnd  from './fish-end.png'
import mainFishStart  from './fish-start.png'
import mainWavesStart from './main-page-start.png'
import fishnetRight from './fish-net-right.png'
import fishnetLeft from './fish-net-left.png'
import sale from './sale.png'
import mainWavesEnd from './main-page-end.png'
export { headerLogo, headerSearch, mainFishEnd, mainFishStart, mainWavesStart, fishnetRight, fishnetLeft, sale,mainWavesEnd};
